HOTKEY = '<HOTKEY>'
NOTE_TAKING_SYSTEM = '<NOTE_TAKING_SYSTEM>'
BLOB_STORAGE_SYSTEM = '<BLOB_STORAGE_SYSTEM>'

ROAM_GRAPH = '<ROAM_GRAPH>'
ROAM_USER = '<ROAM_USER>'
ROAM_PASSWORD = '<ROAM_PASSWORD>'

REMNOTE_USER_ID = '<REMNOTE_USER_ID>'
REMNOTE_API_KEY = '<REMNOTE_API_KEY>'

DROPBOX_ACCESS_TOKEN = '<DROPBOX_ACCESS_TOKEN>'
