HOTKEY = '<HOTKEY>'
NOTE_TAKING_SYSTEM = '<NOTE_TAKING_SYSTEM>'
BLOB_STORAGE_SYSTEM = '<BLOB_STORAGE_SYSTEM>'

ROAM_GRAPH = '<ROAM_GRAPH>'
ROAM_USER = '<ROAM_USER>'
ROAM_PASSWORD = '<ROAM_PASSWORD>'

REMNOTE_USER_ID = '<REMNOTE_USER_ID>'
REMNOTE_API_KEY = '<REMNOTE_API_KEY>'
REMNOTE_ROOT_REM = '<REMNOTE_ROOT_REM>'

IDEAFLOW_USER = '<IDEAFLOW_USER>'
IDEAFLOW_PASSWORD = '<IDEAFLOW_PASSWORD>'

MEM_API_KEY = '<MEM_API_KEY>'

NOTION_INTEGRATION_TOKEN = '<NOTION_INTEGRATION_TOKEN>'
NOTION_DATABASE_ID = '<NOTION_DATABASE_ID>'

TWITTER_API_KEY = '<TWITTER_API_KEY>'
TWITTER_API_SECRET = '<TWITTER_API_SECRET>'
TWITTER_ACCESS_TOKEN = '<TWITTER_ACCESS_TOKEN>'
TWITTER_ACCESS_TOKEN_SECRET = '<TWITTER_ACCESS_TOKEN_SECRET>'

SLACK_API_TOKEN = '<SLACK_API_TOKEN>'
SLACK_CHANNEL_ID = '<SLACK_CHANNEL_ID>'
SLACK_CHANNEL = '<SLACK_CHANNEL>'

EMAIL = '<EMAIL>'
EMAIL_USER = '<EMAIL_USER>'
EMAIL_PASSWORD = '<EMAIL_PASSWORD>'
EMAIL_SERVER = '<EMAIL_SERVER>'

DROPBOX_ACCESS_TOKEN = '<DROPBOX_ACCESS_TOKEN>'

OPENAI_API_KEY = '<OPENAI_API_KEY>'
ANTHROPIC_API_KEY = '<ANTHROPIC_API_KEY>'

WIFI_NETWORKS = []
CUSTOM_COMMAND_PATHS = []
