name: Lint and run Python tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Lint with ruff
        run: |
          ruff .
      - name: Test with pytest
        run: |
          python -m pytest

  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite:2022-04-04
          commands: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install -y git firefox-esr xvfb portaudio19-dev libatlas-base-dev redis-server espeak rustc python3-dev
            mkdir -p /home/pi/code/github/dbieber
            cd /home/pi/code/github/dbieber
            git clone https://github.com/dbieber/GoNoteGo.git
            cd GoNoteGo
            # Checkout the specific commit
            git checkout $GITHUB_SHA
            cp gonotego/settings/secure_settings_template.py gonotego/settings/secure_settings.py
            echo "Manually edit secure_settings.py to configure your settings."
            mkdir /home/pi/secrets
            echo "Manually transfer google_credentials.json to /home/pi/secrets."
            mkdir out
            pip3 install virtualenv
            /home/pi/.local/bin/virtualenv env -p python3
            ./env/bin/pip install grpcio -U --no-binary=grpcio
            ./env/bin/pip install -e .
            echo "Add supervisor start command to /etc/rc.local"
            wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-arm7hf.tar.gz
            tar -xvf geckodriver-v0.23.0-arm7hf.tar.gz
            rm geckodriver-v0.23.0-arm7hf.tar.gz
            sudo mv geckodriver /usr/local/bin
            echo "Set up your internet configuration and audio settings as needed."
            echo "Verify everything's working!"
      - name: Compress the release image
        if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')
        run: |
          mv ${{ steps.build_image.outputs.image }} my-release-image.img
          xz -0 -T 0 -v my-release-image.img
      - name: Upload release image
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')
        with:
          name: Release image
          path: my-release-image.img.xz
